# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.6
  - 7.0
  - 7.1

addons:
  code_climate:
    repo_token: 9a294538179275c2a4a03dd0b6ccf3841635dd6e978f5a51fe789c0c4bd53166

notifications:
  email: false

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --no-interaction

# Commands to be run after your environment runs.
after_script:
  - vendor/bin/test-reporter

# Commands you want to run that will verify your build.
script: vendor/bin/phpunit
